#! /usr/bin/python

import sys

with open(sys.argv[1]) as input_file:
    for line in input_file:
        n,p1,p2 = map(int, line.split(','))
        print str(((n>>(p1-1))&1)==((n>>(p2-1))&1)).lower()
