#!/usr/bin/python

import sys
import itertools

def ispal(i):
  return str(i)==str(i)[::-1]

def compute(L, R):
  for L1 in range(L, R+1):
    for R1 in range(L1, R+1):
      num_pals = 0
      for i in range(L1,R1+1):
        num_pals += ispal(i)
      if num_pals%2 == 0:
        yield num_pals, list(range(L1,R1+1))
       
    

def main():
  for input_file in sys.argv[1:]:
    with open(input_file) as input_file:
      for line in input_file:
        print len(list(compute(*map(int, line.split()))))

main()
          
