#!/usr/bin/python

import sys
import itertools

def permute(line):
    return [''.join(x) for x in itertools.permutations(sorted(line))]

def main():
  for input_file in sys.argv[1:]:
    with open(input_file) as input_file:
      for line in input_file:
        print ','.join(permute(line.strip()))

main()
          
