#!/usr/bin/env python
import os
import re
import sys
import fnmatch

regex = sys.argv[1]
fpatterns = sys.argv[2:]

for root, _, files in os.walk('.'):
  for file in files:
    if (True for pat in fpatterns if fnmatch(file, pat)):
      file = os.path.join(root, file)
      with open(file) as fd:
        for line in fd:
          if re.search(regex, line):
            print file
            break
